version: "2"

services:
  server:
    env_file:
      - .env
    image: python:3.9
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - db
    ports:
      - 3000:3000
    command: python src/server.py

  dbdata:
    image: busybox
    volumes:
      - /data/postgresql/pgdata
  db:
    env_file:
      - .env
    image: postgres:16
    user: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - PGUSER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    volumes_from:
      - dbdata

  testserver:
    env_file: .env
    image: python:3.9
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - testdb
    ports:
      - 5053:5053
    environment:
      APPLICATION_PORT: 5053
      APPLICATION_DB_CONTAINER: testdb
    command: python -m pytest test/

  testdb:
    image: postgres:16
