"""Create Tables

Revision ID: b172c4808961
Revises: None
Create Date: 2024-05-06 07:16:12.545407

"""

# revision identifiers, used by Alembic.
revision = 'b172c4808961'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('first_name', sa.String(length=300), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=300), nullable=True),
    sa.Column('medications', sa.JSON(), nullable=True),
    sa.Column('body_temperatures', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('name', 'first_name')
    )
    op.create_table('user',
    sa.Column('first_name', sa.String(length=300), nullable=False),
    sa.Column('last_name', sa.String(length=300), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('first_name', 'last_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('patient')
    # ### end Alembic commands ###
